In [21]:
A = "PYthon is Easy and Good"
lst = A.split(" ")
lst
B = []
for x in lst:
    if "PYthon" in lst:
        B.append(x)
    else:
        print("No")
B

['PYthon', 'is', 'Easy', 'and', 'Good']

<font size = 5.5> Assignment-1 for Data Science With Python

In [2]:
a1 = [1,2,3,4]
b1 = [11,2,222,33]
a1,b1 = b1,a1
print(a1)
print(b1)

[11, 2, 222, 33]
[1, 2, 3, 4]


In [1]:
import numpy as np

<font size = 4.5> Q1. Swap two columns in a 2d numpy array.

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a[:,[0,1]] = a[:,[1,0]]
a

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [6]:
x = 0
y = 1

a[:,(x,y)] = a[:,(y,x)]
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<font size = 4.5> Q2. Swap two rows in a 2d numpy array.

In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a[[1,2],:] = a[[2,1],:]
a

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [9]:
a[:,[0,1]] = a[:,[1,0]]
a

array([[2, 1, 3],
       [8, 7, 9],
       [5, 4, 6]])

In [10]:
x = 0
y = 1
a[(x,y),:] = a[(y,x),:]
a

array([[8, 7, 9],
       [2, 1, 3],
       [5, 4, 6]])

<font size = 4.5> Q3. Reverse all the rows of a 2d ndarray.

In [11]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a[:,::-1]            #### assign value to a.......then it will work!
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a = a[:,::-1]
a

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [16]:
x = 0 
y = 1
z = 2
a[(x,y,z),:] = a[:,(z,y,x)]   #### Use columns.......Change position of columns....
a

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [15]:
x = 0 
y = 1
z = 2
a[(x,y,z),:] = a[(z,y,x),:]
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

<font size = 4.5>Q4. Extract all numbers between a given range from a one dimensional ndarray.

In [28]:
### Method 1 ........Use of List comprihension.....
y = np.array([2,3,4,5,6,7,89,11,22])
x = np.array([i for i in y if 4<=i<=10])
x

array([4, 5, 6, 7])

In [51]:
### Method 1 .......Use of "for loop".......
y = np.array([2,3,4,5,6,7,89,11,22])
x = []
for i in y:
    if 4<=i<=10:
        x.append(i)
x

[4, 5, 6, 7]

In [17]:
### Method 2
y = np.array([2,3,4,5,6,7,89,11,22])
x = y[(y>=4) and (y<=10)]              ### and will not work here......
x

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [18]:
### Method 2 .......Use of "& bitwise operator".......
y = np.array([2,3,4,5,6,7,89,11,22])
x = y[(y>=4) & (y<=10)]             ###  ...Use of "&" Bitwise Operator....... same as "and" Operator...
x

array([4, 5, 6, 7])

In [19]:
### Method 3
y = np.array([2,3,4,5,6,7,89,11,22])
x = y[(y>=4) * (y<=10)]             ###  ...Use of "*" Mathematical Operator.......
x

array([4, 5, 6, 7])

In [52]:
y = np.array([2,3,4,5,6,7,89,11,22])
y[y>=4]

array([ 4,  5,  6,  7, 89, 11, 22])

In [53]:
y>=10

array([False, False, False, False, False, False,  True,  True,  True])

In [54]:
y[y<=10]

array([2, 3, 4, 5, 6, 7])

In [55]:
y<=10

array([ True,  True,  True,  True,  True,  True, False, False, False])

In [41]:
a[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [34]:
x = a[0]
y = a[1]
x,y = y,x
print(x)
print(y)
a[1] = x
a[0] = y
a

[4 5 6]
[1 2 3]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a[0:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a[::-1]

array([[7, 8, 9],
       [1, 2, 3],
       [1, 2, 3]])

In [20]:
a[0],a[1] = a[1],a[0]
a

array([[1, 2, 3],
       [1, 2, 3],
       [7, 8, 9]])

In [45]:
a[::-2]

array([[7, 8, 9],
       [1, 2, 3]])

In [19]:
a[1,0:3] = a[0,0:3]
a

array([[1, 2, 3],
       [1, 2, 3],
       [7, 8, 9]])

In [11]:
x = a[0,0:3]
y = a[1,0:3]
x,y = y,x
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[0,0:3] = a[1,0:3]
a

array([[4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
x

array([4, 5, 6])

In [14]:
a[0,0:3],a[1,0:3] = a[1,0:3],a[0,0:3]
a

array([[4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

<font size = 4.5> Q5. Given a list of words, find the words with at least 2 vowels. (A,a,E,e,I,i,O,o,U,u)

In [48]:
lst = ["Hello", "Data", "PYthon", "Arjun", "Sheena", "TAvishi", "NomIt"]
Vowel_words = []
for x in lst:
    count = 0
    for i in x:
        if i in "AaEeIiOoUu": count += 1
    if count>=2: Vowel_words.append(x)

In [49]:
Vowel_words

['Hello', 'Data', 'Arjun', 'Sheena', 'TAvishi', 'NomIt']

In [ ]:
lst = ["Hello", "Data", "PYthon", "Arjun", "Sheena", "TAvishi", "NomIt"]
Vowel_words = []
for x in lst:   
    count = 0
    for i in x:
        if i in "AaEeIiOoUu": count += 1
    if count>=2: Vowel_words.append(x)

In [22]:
A = "PYthon is Easy and Good"
lst = A.split(" ")
lst
B = []
for x in lst:
    if "ea" in lst:
        B.append(x)
    else:
        print("No")
B

No
No
No
No
No


[]

In [24]:
A = "PYthon is Easy and Good"
lst = A.split(" ")
lst
B = []
for x in lst:
    if A == "O" and A =="o":
        B.append(x)
    else:
        print("No")
B

No
No
No
No
No


[]

In [25]:
A = "PYthon is Easy and Good"
lst = A.split(" ")
print(lst)
B = []
for x in A:
    if A == "O" and A =="o":
        B.append(x)
    else:
        print("No")
B

['PYthon', 'is', 'Easy', 'and', 'Good']
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No


[]

In [29]:
A = "PYthon is Easy and Good"
lst = A.split(" ")
print(lst)
B = []
for x in A:
    if A == "O" or A =="o":
        B.append(x)
        print(B)
    else:
        print("No")
B

['PYthon', 'is', 'Easy', 'and', 'Good']
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No
No


[]

In [25]:
a[-1:-1:-1]

array([], shape=(0, 3), dtype=int32)

In [2]:
lst = ["PYthon is Easy and Good"]
lst.split(" ")
lst

AttributeError: 'list' object has no attribute 'split'

In [3]:
lst = ["PYthon is Easy and Good"]
lst = lst.split(" ")
lst

AttributeError: 'list' object has no attribute 'split'

In [4]:
A = "PYthon is Easy and Good"
lst = A.split("")
lst

ValueError: empty separator

In [6]:
A = "PYthon is Easy and Good"
lst = A.split(" ")
lst
B = []
for x in lst:
    if a,e,i,o,u in lst:
        B = B.append(x)
        B
    else:
        print()

SyntaxError: invalid syntax (3384456868.py, line 6)

In [17]:
A = "PYthon is Easy and Good"
B = []
for x in A:
    if ("a") in A:
        B = x.append(x)
    else:
        print("No")
B

AttributeError: 'str' object has no attribute 'append'